apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment
spec:
  replicas: 2 # Set the desired number of replicas
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
        - name: dotnet-app
          image: nhtronghai/dotnet-monitoring:latest # Replace with your Docker image name
          ports:
            - containerPort: 5000 # Expose the port specified in your Dockerfile

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-service
spec:
  type: LoadBalancer
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: 3000 
      targetPort: 5000
              
